apiVersion: networking.k8s.io/v1  
kind: Ingress  
metadata:  
  name: todo-ingress  
  namespace: todo  
  labels:  
    app: todo  
  annotations:  
    nginx.ingress.kubernetes.io/rewrite-target: /  
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\" 
